CREATE TABLE customer(
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         full_name VARCHAR NOT NULL,
                         email VARCHAR NOT NULL UNIQUE,
                         social_security_number VARCHAR NOT NULL
);