
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                        creation_date TIMESTAMP NOT NULL,
                        total_cost DOUBLE PRECISION NOT NULL
);


CREATE TABLE products (
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          cost DOUBLE PRECISION NOT NULL
);

CREATE TABLE order_products (
                                order_id INT NOT NULL,
                                product_id INT NOT NULL,
                                PRIMARY KEY (order_id, product_id),
                                FOREIGN KEY (order_id) REFERENCES orders(id),
                                FOREIGN KEY (product_id) REFERENCES products(id)
);