CREATE TABLE sales(
                      id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      product     VARCHAR,
                      price       DECIMAL,
                      quantity    INT
);

INSERT INTO sales (product, price, quantity) VALUES
                                                 ('Laptop', 1000, 5),
                                                 ('Phone', 700, 3),
                                                 ('Tablet', 500, 2),
                                                 ('Printer', 300, 4);

SELECT * FROM sales;

SELECT * FROM sales LIMIT 2;

SELECT SUM(price) FROM sales;

SELECT SUM(quantity) FROM sales;

SELECT product,
       SUM(quantity),
       AVG(price)
FROM sales GROUP BY product;