CREATE TABLE users(
                      id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name    VARCHAR,
                      age     INT,
                      email   VARCHAR
);

INSERT INTO users (name, age, email) VALUES ('John', 30, 'john@example.com');
INSERT INTO users (name, age, email) VALUES ('Alice', 25, 'alice@example.com');
INSERT INTO users (name, age, email) VALUES ('Bob', 35, 'bob@example.com');

SELECT * FROM users;

DELETE FROM users WHERE name='Bob';